"use client";

import { FormEvent, useEffect, useState } from "react";
import { Check, Plus } from "lucide-react";
import { PartnerApplication, StoreSettings } from "../../types";
import { defaultStoreSettings } from "../../lib/store-config";
import { DRC_PROVINCES } from "../../lib/drc-geography";
import { getStoreSettings, updateStoreSettings } from "../../services/db/settings";
import { getPartnerApplications } from "../../services/db/partner-applications";
import { getDeliveryZones, saveDeliveryZone, updatePartnerApplicationStatus } from "../../services/db/marketplace";

export function BusinessControls() {
  const [settings, setSettings] = useState<StoreSettings>(defaultStoreSettings); const [applications, setApplications] = useState<PartnerApplication[]>([]); const [zones, setZones] = useState<StoreSettings["delivery_zones"]>([]); const [notice, setNotice] = useState("");
  const [zone, setZone] = useState({ province: "Nord-Kivu", city: "Goma", fee: "0", currency: "USD" as const });
  const load = () => Promise.all([getStoreSettings(), getPartnerApplications(), getDeliveryZones(true)]).then(([store, apps, deliveryZones]) => { setSettings(store); setApplications(apps); setZones(deliveryZones); }).catch((error: unknown) => setNotice(error instanceof Error ? error.message : "Unable to load business controls."));
  useEffect(() => { load(); }, []);
  async function saveSettings(event: FormEvent) { event.preventDefault(); try { const next = await updateStoreSettings(settings); setSettings(next); setNotice("Business settings saved."); } catch { setNotice("Settings could not be saved."); } }
  async function addZone(event: FormEvent) { event.preventDefault(); try { await saveDeliveryZone({ country: "CD", province: zone.province, city: zone.city || undefined, active: true, fee: Number(zone.fee), currency: zone.currency }); setZone({ province: "Nord-Kivu", city: "Goma", fee: "0", currency: "USD" }); await load(); setNotice("Delivery zone added."); } catch { setNotice("Delivery zone could not be saved."); } }
  async function setStatus(id: string, status: PartnerApplication["status"]) { try { await updatePartnerApplicationStatus(id, status); await load(); } catch { setNotice("Application status could not be updated."); } }
  return <div className="space-y-8"><div><h2 className="text-xl font-bold">Business control centre</h2><p className="mt-1 text-sm text-muted-foreground">Launch, official contacts, delivery availability, and partner applications.</p></div>{notice && <p role="status" className="rounded-lg bg-muted p-3 text-sm">{notice}</p>}
    <form onSubmit={saveSettings} className="grid gap-4 rounded-2xl border border-border bg-card p-5 md:grid-cols-2"><h3 className="md:col-span-2 font-semibold">Store and launch</h3><Input label="Store name" value={settings.name} onChange={(name) => setSettings({ ...settings, name })}/><Input label="Tagline" value={settings.tagline} onChange={(tagline) => setSettings({ ...settings, tagline })}/><label className="text-sm font-medium">Launch mode<select value={settings.launch.mode} onChange={(e) => setSettings({ ...settings, launch: { ...settings.launch, mode: e.target.value as StoreSettings["launch"]["mode"] } })} className="mt-1 block w-full rounded-lg border border-border bg-background p-2"><option value="active">Marketplace active</option><option value="coming_soon">Coming soon</option></select></label><label className="text-sm font-medium">Launch date and time<input type="datetime-local" value={settings.launch.starts_at ? settings.launch.starts_at.slice(0, 16) : ""} onChange={(e) => setSettings({ ...settings, launch: { ...settings.launch, starts_at: e.target.value ? new Date(e.target.value).toISOString() : null } })} className="mt-1 block w-full rounded-lg border border-border bg-background p-2" /></label><label className="md:col-span-2 text-sm font-medium">Launch message<textarea value={settings.launch.announcement} onChange={(e) => setSettings({ ...settings, launch: { ...settings.launch, announcement: e.target.value } })} rows={3} className="mt-1 block w-full rounded-lg border border-border bg-background p-2" /></label><h3 className="md:col-span-2 mt-3 font-semibold">Official contact channels</h3><Input label="Buy via WhatsApp number" value={settings.whatsapp_buy_number || ""} onChange={(whatsapp_buy_number) => setSettings({ ...settings, whatsapp_buy_number })}/><p className="self-end text-xs text-muted-foreground">Shared DLX business number for product ordering; leave blank to hide the button.</p>{(["general", "support", "orders", "delivery", "partnerships"] as const).map((role) => <div key={role} className="rounded-lg border border-border p-3"><p className="mb-2 text-xs font-bold uppercase">{role}</p><Input label="Email" value={settings.contacts[role]?.email || ""} onChange={(email) => setSettings({ ...settings, contacts: { ...settings.contacts, [role]: { ...settings.contacts[role], email } } })}/><Input label="Phone" value={settings.contacts[role]?.phone || ""} onChange={(phone) => setSettings({ ...settings, contacts: { ...settings.contacts, [role]: { ...settings.contacts[role], phone } } })}/><Input label="WhatsApp" value={settings.contacts[role]?.whatsapp || ""} onChange={(whatsapp) => setSettings({ ...settings, contacts: { ...settings.contacts, [role]: { ...settings.contacts[role], whatsapp } } })}/></div>)}<button className="md:col-span-2 inline-flex items-center justify-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground"><Check className="h-4 w-4" />Save business settings</button></form>
    <section className="rounded-2xl border border-border bg-card p-5"><h3 className="font-semibold">Delivery zones</h3><form onSubmit={addZone} className="mt-4 grid gap-3 sm:grid-cols-4"><select value={zone.province} onChange={(e) => setZone({ ...zone, province: e.target.value })} className="rounded-lg border border-border bg-background p-2">{DRC_PROVINCES.map((province) => <option key={province}>{province}</option>)}</select><input value={zone.city} onChange={(e) => setZone({ ...zone, city: e.target.value })} placeholder="City / territory / commune" className="rounded-lg border border-border bg-background p-2"/><input min="0" type="number" value={zone.fee} onChange={(e) => setZone({ ...zone, fee: e.target.value })} className="rounded-lg border border-border bg-background p-2"/><button className="inline-flex items-center justify-center gap-1 rounded-lg border border-border p-2 text-sm font-semibold"><Plus className="h-4 w-4" />Add zone</button></form><ul className="mt-4 divide-y divide-border text-sm">{zones.length ? zones.map((item, index) => <li key={`${item.province}-${item.city}-${index}`} className="py-2">{item.province}{item.city ? ` · ${item.city}` : ""} — {item.fee} {item.currency}</li>) : <li className="py-2 text-muted-foreground">No delivery zones configured.</li>}</ul></section>
    <section className="rounded-2xl border border-border bg-card p-5"><h3 className="font-semibold">Partner applications</h3><div className="mt-4 space-y-3">{applications.length ? applications.map((application) => <article key={application.id} className="rounded-lg border border-border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{application.business_name}</p><p className="text-sm text-muted-foreground">{application.owner_name} · {application.province}, {application.city}</p><p className="mt-2 text-sm">{application.description}</p></div><select value={application.status} onChange={(e) => setStatus(application.id, e.target.value as PartnerApplication["status"])} className="rounded-lg border border-border bg-background p-2 text-sm"><option value="pending">Pending</option><option value="reviewing">Reviewing</option><option value="approved">Approved</option><option value="declined">Declined</option></select></div></article>) : <p className="text-sm text-muted-foreground">No applications yet.</p>}</div></section></div>;
}
function Input({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="mb-2 block text-sm font-medium">{label}<input value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 block w-full rounded-lg border border-border bg-background p-2" /></label>; }
